### ISSUE TITLE
No video on iOS emulator. 

### ISSUE THREAD

**Issue by marcopogo81** [DimitrisTzimikas/rnWebRTC#1]
Hi,

 i'm new to ios, all the stuff works as expected, it asks for camera and audio, but no video is displayed for ios in the simulator.

**Comment by DimitrisTzimikas** [comment]
Yea, I am running my tests on iOS & Android devices because I think there was a section on README.md in the old react-native-webrtc repo that said you can't run it on emulators. 

Give it a try on a real device and come back with the results.
